//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int IDProduktu { get; set; }
        public int IDKategorii { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public decimal CenaZaDobe { get; set; }
        public decimal Kaucja { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
    }
}
