//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PelnyProdukt
    {
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public decimal CenaZaDobe { get; set; }
        public decimal Kaucja { get; set; }
        public string Kategoria { get; set; }
        public string Miasto { get; set; }


        override public string ToString()
        {
            return $"{ID}: {Marka} {Model} Miasto: {Miasto}";
        }
    }
}
