//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktySz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProduktySz()
        {
            this.RezerwacjeSzs = new HashSet<RezerwacjeSz>();
            this.WypozyczenieSzs = new HashSet<WypozyczenieSz>();
        }
    
        public int IDProduktuSZ { get; set; }
        public Nullable<int> IDProduktu { get; set; }
        public Nullable<int> IDPunktuObslugi { get; set; }
        public int Stantechniczny { get; set; }
    
        public virtual Produkty Produkty { get; set; }
        public virtual PunktyObslugi PunktyObslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezerwacjeSz> RezerwacjeSzs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieSz> WypozyczenieSzs { get; set; }
    }
}
