//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenie()
        {
            this.WypozyczenieSz = new HashSet<WypozyczenieSz>();
        }
    
        public int IDWypozyczenia { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public System.DateTime DataDoZwrotu { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczenieSz> WypozyczenieSz { get; set; }
    }
}
