//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WypozyczenieView
    {
        public int ID { get; set; }
        public string Klient { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public System.DateTime DataDoZwrotu { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
        public string Narzędzie { get; set; }
        public string PunktObslugi { get; set; }
        public decimal Kaucja { get; set; }
        public Nullable<decimal> Cena { get; set; }
    }
}
