//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WypozyczenieSz
    {
        public int IDWypozyczeniaSZ { get; set; }
        public Nullable<int> IDWypozyczenia { get; set; }
        public Nullable<int> IDProduktuSz { get; set; }
        public string IDKlienta { get; set; }
        public string IDPracWydajacego { get; set; }
        public string IDPracOdbierajacego { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
        public virtual ProduktySz ProduktySz { get; set; }
        public virtual Wypozyczenie Wypozyczenie { get; set; }
    }
}
